[build]
  command = "npm run build"
  publish = "build"

# Handle React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "16"
  CI = "false"
  REACT_APP_NODE_ENV = "production" 